### ISSUE TITLE
Difference in the output

### ISSUE THREAD

**Issue by tinohager** [barnhill/barcodelib#134] opened 2021-08-18 19:24 UTC
We have been using `NetBarcode` until now, and are currently looking into switching to their project. We have noticed a difference in the output.

For the topmost Code 39 barcode, the last bar is shorter and the image is shifted one pixel to the right. The same happens with code 128, i have only checked the 2 so far.

```
var barcodeElement = new BarcodeLib.Barcode();
barcodeElement.BarWidth = 3;
barcodeElement.BackColor = Color.Transparent;
barcodeElement.Height = 100;
using var image = barcodeElement.Encode(BarcodeLib.TYPE.CODE39, "123ABC");
```

barcodelib
![image](https://user-images.githubusercontent.com/8215186/129958964-a110c5de-0ff4-455f-bbec-9a99f23cc021.png)

NetBarcode 
![image](https://user-images.githubusercontent.com/8215186/129958933-35a8fd86-54be-40a2-9dfb-502992b68161.png)

**Comment by yuriyolshevskyy** [comment] 2021-09-01 19:14
The compiled EXE encodes UPC-A 000000123456 that reads 000000123457 by the scanner.
![image](https://user-images.githubusercontent.com/35158269/131730264-78e6f2c6-0a0e-4dee-8e10-a82e97302c41.png)

**Comment by barnhill** [comment] 2023-04-03 02:43
This is most likely caused by an invalid check digit being on the end so its recalculating it.  So its correcting the bad data being input.  If you input `00000012345` it will scan as the same as its calculating the check digit even if the input is invalid so that it is a valid barcode.

**Comment by barnhill** [comment] 2023-04-03 02:46
I believe the issue with the barcode being shifted to the right by one pixel has been fixed in a previous release.  I just tested it just now with a width that barely fits the barcode with multiple pixel bars and it centers and draws the bars to the edges just like expected.

**Closed** 2023-04-03 02:46 UTC
