### ISSUE TITLE
Generating UPC-E code doesn't work properly

### ISSUE THREAD

**Issue by aanklewicz92** [barnhill/barcodelib#7] opened 2015-05-15 13:38 UTC
Hello,

I'm working on generating barcodes in my C# application and for UPC-E codes I'm using BarcodeLib. Unfortunatelly I have noticed that barcodes aren't generated properly. I've tested few online generators and all of them are generating the same barcode when BarcodeLib generates different. Example below.

Barcode generated online:
![upc-e_04252614](https://cloud.githubusercontent.com/assets/11396814/7653521/92e5e19e-fb16-11e4-83f8-75e34836f439.jpg)
Barcode generated by BarcodeLib:
![barcodelib](https://cloud.githubusercontent.com/assets/11396814/7653527/9b768e76-fb16-11e4-8fc0-9d3b441f4eca.png)

As you can see even three first stripes aren't the same.
For generating barcode I'm using following code:

var barcode = new Barcode();
Image img = barcode.Encode(TYPE.UPCE, content, Color.Black, Color.White, 300, 150);

content is String containing number. In this example "425261". 
Could you please give me some informations why codes aren't generated properly?

Thanks for any help

**Comment by bbarnhill** [comment] 2015-05-22 15:05
interesting ... I just confirmed this online with an online reader.  Looks like Ill have to investigate this.  If you see why its doing it feel free to create a pull request to fix it.

**Comment by bbarnhill** [comment] 2015-08-30 22:24
I just tried to find the issue and its encoding just fine for me.  The first image is of it generating the barcode in the example app in this project.  The second is a screenshot of it being recognized as upce in an online barcode reader.

![proof](https://cloud.githubusercontent.com/assets/3878158/9569802/e37dae60-4f3b-11e5-9083-a21a59d484ca.png)
![proof2](https://cloud.githubusercontent.com/assets/3878158/9569803/e381a6b4-4f3b-11e5-838a-c5addc99c5f2.png)

**Comment by Episodex** [comment] 2015-08-31 06:28
I'm from the same team as @aanklewicz92 . I don't now remember all the details but I think the problem was that barcodelib allowed and generated barcodes with wrong check digit, but I can't be 100% sure now.
Anyway our final solution was to take the input, convert it digit-by-digit to UPC-A and then encode this UPC-A using barcodelib which worked in all cases. So maybe the problem is in decoding UPC-E to UPC-A in barcodelib?

This is the algorithm we used and it works:

            //algorithm: http://www.barcodeisland.com/upce.phtml
            if(upce.Length != 8)
                throw new ArgumentException("Wrong UPC-E length. Only 8 digits format allowed.");

            var lastDigit = upce.Substring(6, 1);
            var result = upce.Substring(0, 1);

            if (lastDigit == "0" || lastDigit == "1" || lastDigit == "2")
            {
                result += upce.Substring(1, 2);
                result += upce.Substring(6, 1);
                result += "0000";
                result += upce.Substring(3, 3);

            }
            else if (lastDigit == "3")
            {
                result += upce.Substring(1, 3);
                result += "00000";
                result += upce.Substring(4, 2);
            } 
            else if (lastDigit == "4")
            {
                result += upce.Substring(1, 4);
                result += "00000";
                result += upce.Substring(5, 1);
            }
            else
            {
                result += upce.Substring(1, 5);
                result += "0000";
                result += upce.Substring(6, 1);
            }

            result += upce.Substring(7, 1);

            return result;

**Comment by aanklewicz92** [comment] 2016-05-06 10:14
It's been a while, but this may be useful. I found out that NuGet library version is somehow bugged. Localy generated DLL works fine.

**Comment by barnhill** [comment] 2016-07-30 00:39
you are correct ... Sorry I took so long to respond.  I totally missed this
email till I was cleaning out my email box.  I have a fix for it as its a 1
char change in the code that caused this.  I will have the code updated in
a few minutes even though I doubt you waited on this fix.  Sorry again for
not seeing this and I really have no excuse.  I value your input and I
really am glad that you took the time to post this.

THANKS again for your help finding this and Im glad you use open source
software.

Brad Barnhill
bradbarnhill@hotmail.com
www.bradbarnhill.com

**Comment by takwirira** [comment] 2016-07-30 07:47
No problem and thank you for following up and posting a fix. I'm sure it'll
help!

**Comment by barnhill** [comment] 2016-08-01 04:25
Fixed with https://github.com/barnhill/barcodelib/commit/886eb9a865ba62a4014a272ddca83d58eaeb7260

**Closed by barnhill** 2016-08-01 04:25 UTC
Labels: help wanted
